name: c_widget
description: "Custom Widget"
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: '>=3.2.1<4.0.0'

 
dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_provider: ^2.1.0
  provider: ^6.1.2
  flutter_bloc: ^8.1.4
  intl: ^0.20.2
  searchable_dropdown:
    git:
      url: https://github.com/alokemscit/searchable_dropdown.git
      ref: main  
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

 
flutter:

  
  uses-material-design: true
 
